import { FirestoreDataConverter, Timestamp } from "firebase-admin/firestore";

// Translation interface to define the structure of the translation data
export interface Translation {
  translation_id: string;
  user_id: string; // Reference to the user who created the translation
  text_english: string; // English text input by the user
  text_japanese: string; // Japanese translation generated by OpenAI
  audio_english: string; // URL to the generated English audio file
  audio_japanese: string; // URL to the generated Japanese audio file
  created_at: Timestamp; // Timestamp for when the translation was created
  likes: number; // Number of likes this translation has received
}

// Firestore data converter for consistent formatting when interacting with Firestore
export const translationConverter: FirestoreDataConverter<Translation> = {
  toFirestore(translation: Translation): FirebaseFirestore.DocumentData {
    return {
      user_id: translation.user_id,
      text_english: translation.text_english,
      text_japanese: translation.text_japanese,
      audio_english: translation.audio_english,
      audio_japanese: translation.audio_japanese,
      created_at: translation.created_at,
      likes: translation.likes,
    };
  },
  fromFirestore(
    snapshot: FirebaseFirestore.QueryDocumentSnapshot
  ): Translation {
    const data = snapshot.data()!;
    return {
      translation_id: snapshot.id,
      user_id: data.user_id,
      text_english: data.text_english,
      text_japanese: data.text_japanese,
      audio_english: data.audio_english,
      audio_japanese: data.audio_japanese,
      created_at: data.created_at,
      likes: data.likes,
    };
  },
};
